### ISSUE TITLE
fluttery ... requires SDK version >=1.19.0 <2.0.0, version solving failed

### ISSUE THREAD

**Issue by rai2270** [matthew-carroll/flutter_ui_challenge_music_player#7]
fluttery issue:
fluttery ... requires SDK version >=1.19.0 <2.0.0, version solving failed

**Comment by rai2270** [comment]
I took the entire fluttery into this project to resolve this

**Comment by yasahmed** [comment]
i have the same issue !, did u find any solution ?

**Comment by rai2270** [comment]
I think I was able to make it to compile (eventually) , but it was showing the spectrum only in android. not in iOS.  It was a month ago, so need to find the fix. I'll check a bit later.

**Comment by yash365** [comment]
try to update the fluttery_audio plugin with
dependencies:
  fluttery_audio: ^0.0.4

i should should solve the error

**Comment by thelovesmith** [comment]
I am also having this issue with fluttery. When I update fluttery_audio:^0.0.4; the error persists

**Comment by ogulcandogan** [comment]
I had the same problem and I fix it with update. You can find last version in https://pub.dartlang.org/packages/
but I am writing for you for this time :)
 fluttery: 0.0.8
  fluttery_audio: 0.0.4
